[package]
name = "xitca-postgres-diesel"
version = "0.3.0"
edition = "2024"

[features]
default = ["instrumentation"]
instrumentation = []

[dependencies]
diesel = { version = "2", features = ["postgres_backend", "i-implement-a-third-party-backend-and-opt-into-breaking-changes"] }
tokio = { version = "1.40.0", features = ["sync"] }
xitca-postgres = { version = "0.4.0" }

[dev-dependencies]
diesel-async = { version = "0.7.3", features = ["bb8", "postgres"] }
futures-util = "0.3"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
